aplicacion/cuenta/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email
from flask_babel import _

class Formulariologin(FlaskForm): 
    usuariologin = StringField(_('Username'), validators=[DataRequired(_("User name required"))])
    contrasenialogin = PasswordField(_("Password"), validators=[DataRequired(_("Password required"))])
    submitlogin = SubmitField(_('Sign in'))

class Formularioregistro(FlaskForm): 
    usuarioreg = StringField(_('Username'), validators=[DataRequired(_("User name required"))])
    correoreg = StringField(_("E-mail"), validators=[DataRequired(_("E-mail required")),Email()])
    contraseniareg = PasswordField(_("Password"), validators=[DataRequired(_("Password required"))])
    submitreg = SubmitField(_('Sign up'))

aplicacion/cuenta/__init__.py
from flask import Blueprint

cuenta = Blueprint('cuenta', __name__, template_folder='templates', static_folder='static/css')

from . import routes

aplicacion/cuenta/routes.py
import os
from flask import current_app ,render_template, request, url_for, redirect, flash, session
from flask_mail import Message
from flask_babel import _
import sqlite3
from . import cuenta
from aplicacion.cuenta.forms import Formulariologin, Formularioregistro

def send_confirmation_email(email):
    from aplicacion import serializer, mail
    token = serializer.dumps(email, salt='email-confirm')
    confirmation_url = url_for('cuenta.confirm_email', token=token, _external=True)

    message = Message('Confirm your email', recipients=[email])
    message.body = f"Click the link to confirm your email: {confirmation_url}"

    try:
        mail.send(message)
    except Exception as e:
        print(f"Error sending email: {e}")

@cuenta.route('/login', methods=["GET", "POST"])
def login():

    # Check if the user is already logged in
    if 'user_id' in session:
        flash(_('You are already logged in'), 'info')
        return redirect(url_for('catalogo.pagina_catalogo'))

    form = Formulariologin(request.form)

    if form.validate_on_submit():
        username = form.usuariologin.data
        password = form.contrasenialogin.data

        print("Intentando acceder a la base de datos desde la ruta:", os.getcwd())

        conn = sqlite3.connect('aplicacion/database/ebanisteria.db')
        cursor = conn.cursor()

        # Buscar el usuario en la base de datos
        cursor.execute('SELECT * FROM User WHERE nom_usuario = ?', (username,))
        user = cursor.fetchone()

        if user and user[3] == 1 and user[4] == password:
            
            session['logged_in'] = True
            session['user_id'] = user[0]
            session['admin'] = user[5]
            session['username'] = user[1]

            flash(_('Inicio de sesión exitoso'), 'success')
            return redirect(url_for('catalogo.pagina_catalogo'))
        else:
            flash(_('Wrong username or password'), 'danger')

    return render_template('cuentalog.html', form=form)

@cuenta.route('/registro', methods=["GET", "POST"])
def registro():

    # Check if the user is already logged in
    if 'user_id' in session:
        flash(_('You are already logged in'), 'info')
        return redirect(url_for('catalogo.pagina_catalogo'))

    form = Formularioregistro(request.form)

    if form.validate_on_submit():
        usuarioreg = form.usuarioreg.data
        email = form.correoreg.data
        password = form.contraseniareg.data

        conn = sqlite3.connect('aplicacion/database/ebanisteria.db')
        cursor = conn.cursor()

        # Verificar si el usuario ya existe
        cursor.execute('SELECT * FROM User WHERE nom_usuario = ? OR correo = ?', (usuarioreg, email))
        existing_user = cursor.fetchone()

        if existing_user:
            flash(_('User or email already in use'), 'danger')
            conn.close()
        else:

            # Determine if this is the first user
            cursor.execute('SELECT COUNT(*) FROM User')
            user_count = cursor.fetchone()[0]

            # Set admin field based on user count
            admin = 1 if user_count == 0 else 0

            # Insert the user into the User table
            cursor.execute('INSERT INTO User (nom_usuario, correo, contrasenia, admin, verificado) VALUES (?, ?, ?, ?, ?)',
                           (usuarioreg, email, password, admin, 0))
            conn.commit()
            conn.close()

            send_confirmation_email(email)
            flash(_('Check your email for a confirmation link.'), 'success')
            return redirect(url_for("cuenta.login"))

    return render_template('registro.html', form=form)

@cuenta.route('/logout', methods=["POST"])
def logout():
    # Clear the user session
    session.clear()
    flash(_('Successfully logged out'), 'success')
    return redirect(url_for('catalogo.pagina_catalogo'))

@cuenta.route('/confirm/<token>')
def confirm_email(token):
    ruta = current_app.config['DATABASE_URI'].replace('sqlite:///', '')
    conexion = sqlite3.connect('aplicacion/database/ebanisteria.db')

    cursor = conexion.cursor()

    try:
        from aplicacion import serializer
        email = serializer.loads(token, salt='email-confirm', max_age=3600)
        
        cursor.execute('SELECT * FROM User WHERE correo = ?', (email,))
        usuario = cursor.fetchone()

        if usuario:
            # Update the user's confirmation status
            cursor.execute('UPDATE User SET verificado = 1 WHERE id = ?', (usuario[0],))
            conexion.commit()

            flash(_('Email confirmed successfully!'), 'success')
        else:
            flash(_('User not found.'), 'danger')
    except:
        flash(_('The confirmation link is invalid or has expired.'), 'danger')
    finally:
        conexion.close()

    return redirect(url_for('cuenta.login'))

aplicacion/cuenta/templates/cuentalog.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{url_for('cuenta.static', filename='styles.css')}}">

{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}
    <body class="body-cuenta">
        <div class="container login-container">
            <div class="row justify-content-center">
                <div class="col-md-6 col-sm-12">
                    <div class="card">
                        <div class="card-header text-center bg-dark text-white">
                            <h3>{{ _('My personal account') }}</h3>
                        </div>
                        <div class="card-body">
                            <form action="{{url_for('cuenta.login')}}" method="POST" novalidate>
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    {{form.usuariologin.label()}} {{form.usuariologin(class="form-control",
                                    placeholder=_("Write your user name"))}}
                                </div>
                                <!-- validacion de errores -->
                                {% if form.usuariologin.errors %}
                                <div class="alert alert-danger">
                                    {{ form.usuariologin.errors[0] }}
                                </div>
                                {% endif %}

                                <div class="form-group">
                                    {{form.contrasenialogin.label()}} {{form.contrasenialogin(class="form-control",
                                    placeholder=_("Write your password"))}}
                                </div>
                                <!-- validacion de errores -->
                                {% if form.contrasenialogin.errors %}
                                <div class="alert alert-danger">
                                    {{ form.contrasenialogin.errors[0] }}
                                </div>
                                {% endif %}
                                {{form.submitlogin(class="btn btn-dark btn-block")}}
                            </form>
                            <div class="text-center mt-3">
                                <p>{{ _('Not registered yet?') }} <a href="{{ url_for('cuenta.registro') }}">{{_('Sign up here')}}</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Agrega la referencia a Bootstrap JS y Popper.js -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    </body>

<!-- Display flash messages -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endwith %}

{% endblock %}

aplicacion/cuenta/templates/registro.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{url_for('cuenta.static', filename='styles.css')}}">

{% extends "base.html" %}
{% block title %} Registro {% endblock %}

{% block content %}

<body class="body-cuenta">
    <div class="container register-container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-header text-center bg-dark text-white">
                        <h3>{{ _('Sign up') }}</h3>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {{ form.csrf_token }}
                            <div class="form-group">
                            {{form.usuarioreg.label()}} {{form.usuarioreg(class="form-control", placeholder=_("Choose a user name"))}}
                            </div>
                            <!-- validacion de errores -->
                            {% if form.usuarioreg.errors %}
                            <div class="alert alert-danger">
                            {{ form.usuarioreg.errors[0] }}
                            </div>
                            {% endif %}

                            <div class="form-group">
                            {{form.correoreg.label()}} {{form.correoreg(class="form-control", placeholder=_("Write your E-mail"))}}
                            </div>
                            <!-- validacion de errores -->
                            {% if form.correoreg.errors %}
                            <div class="alert alert-danger">
                            {{ form.correoreg.errors[0] }}
                            </div>
                            {% endif %}
                            
                            <div class="form-group">
                            {{form.contraseniareg.label()}} {{form.contraseniareg(class="form-control", placeholder=_('Choose a password'))}}
                            </div>
                            <!-- validacion de errores -->
                            {% if form.contraseniareg.errors %}
                            <div class="alert alert-danger">
                            {{ form.contraseniareg.errors[0] }}
                            </div>
                            {% endif %}
                            {{form.submitreg(class="btn btn-dark btn-block")}}
                        </form>
                        <div class="text-center mt-3">
                            <p>{{_('Already have an account?')}} <a href="{{ url_for('cuenta.login') }}">{{_('Sign in here')}}</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Agrega la referencia a Bootstrap JS y Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>

<!-- Display flash messages -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
  {% for message in messages %}
  <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endwith %}

{% endblock %}